### ISSUE TITLE
what format should the csv file have?

### ISSUE THREAD

**Issue by beiex** [tintinweb/ecdsa-private-key-recovery#14]
Hi and thx 4 the tool
rusty block parser seems to have undergone some changes and since I don't know how to correctly adjust your patch I'm getting 
IndexError('list index out of range',)
when I try to import my csv that contains 
txid,script
txid,script
txid,script
...

so how does it have to look like for it to work? (tried unchanged rusty output as well but did fail)

btw. do you have some code snippets that use the rpc call (although slow) since I'm using that anyway and since I'm only "playing" around I don't care if its slow.. 

thx up front

**Comment by trextrader** [comment]
> Hi and thx 4 the tool
> rusty block parser seems to have undergone some changes and since I don't know how to correctly adjust your patch I'm getting
> IndexError('list index out of range',)
> when I try to import my csv that contains
> txid,script
> txid,script
> txid,script
> ...
> 
> so how does it have to look like for it to work? (tried unchanged rusty output as well but did fail)
> 
> btw. do you have some code snippets that use the rpc call (although slow) since I'm using that anyway and since I'm only "playing" around I don't care if its slow..
> 
> thx up front

Having similar issues I am attaching a copy of the csvdump file which I used to save in src\callbacks and changed the name of the original file to csvdump_old.  

_Please note their extensions changed to .txt in order to upload here on github_

Apparently I am doing something wrong here as when trying to re-create using cargo build --release it throws several errors.  Also tried to just run the parser using ./blockparser csvdump /rusty-blockparser/csvdump.txt

And obviously that did not work either...

Much appreciated any help you can give, or better, rather than just providing a patch, provide the actual csvdump.rs file to overwrite or replace the original before re-building so its as simple as:

1) Replace this file at this folder location
2) from root of Rusty-Blockparser enter the following: cargo build --release
3) Next enter the following:  ./blockparser csvdump /rusty-blockparser/csvdump.txt

...COFFEE BREAK...

4) and follow next steps once it has completed.

**That would certainly make this much more simple to follow along the yellow brick road and not get met by the wicked witch of the west trying to rain on our parade!** :)

/Zap
[csvdump.txt](https://github.com/tintinweb/ecdsa-private-key-recovery/files/6013961/csvdump.txt)
[csvdump_orig.txt](https://github.com/tintinweb/ecdsa-private-key-recovery/files/6013962/csvdump_orig.txt)

**Comment by trextrader** [comment]
> > Hi and thx 4 the tool
> > rusty block parser seems to have undergone some changes and since I don't know how to correctly adjust your patch I'm getting
> > IndexError('list index out of range',)
> > when I try to import my csv that contains
> > txid,script
> > txid,script
> > txid,script
> > ...
> > so how does it have to look like for it to work? (tried unchanged rusty output as well but did fail)
> > btw. do you have some code snippets that use the rpc call (although slow) since I'm using that anyway and since I'm only "playing" around I don't care if its slow..
> > thx up front
> 
> Having similar issues I am attaching a copy of the csvdump file which I used to save in src\callbacks and changed the name of the original file to csvdump_old.
> 
> _Please note their extensions changed to .txt in order to upload here on github_
> 
> Apparently I am doing something wrong here as when trying to re-create using cargo build --release it throws several errors. Also tried to just run the parser using ./blockparser csvdump /rusty-blockparser/csvdump.txt
> 
> And obviously that did not work either...
> 
> Much appreciated any help you can give, or better, rather than just providing a patch, provide the actual csvdump.rs file to overwrite or replace the original before re-building so its as simple as:
> 
> 1. Replace this file at this folder location
> 2. from root of Rusty-Blockparser enter the following: cargo build --release
> 3. Next enter the following:  ./blockparser csvdump /rusty-blockparser/csvdump.txt
> 
> ...COFFEE BREAK...
> 
> 1. and follow next steps once it has completed.
> 
> **That would certainly make this much more simple to follow along the yellow brick road and not get met by the wicked witch of the west trying to rain on our parade!** :)
> 
> /Zap
> [csvdump.txt](https://github.com/tintinweb/ecdsa-private-key-recovery/files/6013961/csvdump.txt)
> [csvdump_orig.txt](https://github.com/tintinweb/ecdsa-private-key-recovery/files/6013962/csvdump_orig.txt)

I am making some progress! Still showing a couple errors so I went ahead with the original rust script for cvsdump.rs and now I have tx_in.csv.tmp, I have d-loaded mysql, and followed your instructions precisely to this point...not sure if I am setting up this database correctly or not, but we shall soon see..see screenshot and attached is the latest attempt to get your version of cvsdump to build - not so much, perhaps you can give it a quick review and let me know what exactly I am doing incorrectly?

/Zap
[csvdumpv2.txt](https://github.com/tintinweb/ecdsa-private-key-recovery/files/6026050/csvdumpv2.txt)
![current state 2-22-21](https://user-images.githubusercontent.com/24986102/108786777-934bd580-7531-11eb-866d-dfecab9f9894.PNG)
