### ISSUE TITLE
 No module named setuptools

### ISSUE THREAD

**Issue by liodragon** [tintinweb/ecdsa-private-key-recovery#21]
(.env27) me@DESKTOP-QLRBDDE:~/ecdsa-private-key-recovery$ sudo python2.7 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by amritabithi** [comment]
> (.env27) me@DESKTOP-QLRBDDE:~/ecdsa-private-key-recovery$ sudo python2.7 setup.py install Traceback (most recent call last): File "setup.py", line 5, in from setuptools import setup, find_packages ImportError: No module named setuptools

Try this command from the /ecdsa-private-key-recovery/ folder on your computer:

`sudo python3 setup.py install`

**- Also I just installed python fresh on my system using the command:**
**sudo apt-get install python**

**Comment by liodragon** [comment]
OK, just installed python 2.7...
after run > sudo apt-get install python
got it setup of py 2.7...
Setting up python-is-python2 (2.7.17-4) ...
after than run > python tests/test_ecdsa_key_recovery.py
return Got Final line error:::>

"
Traceback (most recent call last):
  File "tests/test_ecdsa_key_recovery.py", line 5, in <module>
    from Crypto.Random import random
ImportError: No module named Crypto.Random
"
PS 
Thank you to your prompt Replay

**Comment by amritabithi** [comment]
> OK, just installed python 2.7... after run > sudo apt-get install python got it setup of py 2.7... Setting up python-is-python2 (2.7.17-4) ... after than run > python tests/test_ecdsa_key_recovery.py return Got Final line error:::>
> 
> " Traceback (most recent call last): File "tests/test_ecdsa_key_recovery.py", line 5, in from Crypto.Random import random ImportError: No module named Crypto.Random " PS Thank you to your prompt Replay

For the missing Crypto.Random errorr, try doing this command to install the missing modules:
`sudo apt-get install python-dev`

I had to fix a couple of bugs and still have not got the test working yet, as it is telling me the test string does not fall along the elliptical curve function in any format, so I have not been able to run it fully yet either.  If I do get it working or get an alternative working that I am going to try I will upload the instructions of what I did... 

I had to change a part of the code that was deprecated, so the error about the time clock is fixed by changing "time.clock()" to time.perf_counter() , and I am still working on an encoding bug that I will let you know if I can get working.

**Comment by liodragon** [comment]
Thank to quick Re...
Got install python-dev 2.7 - so after that again return error /either with command python or pytnon2.7/
sudo or pure 
python tests/test_ecdsa_key_recovery.py
"
Traceback (most recent call last):
  File "tests/test_ecdsa_key_recovery.py", line 5, in <module>
    from Crypto.Random import random
ImportError: No module named Crypto.Random
"

**Comment by tintinweb** [comment]
added more details to https://github.com/tintinweb/ecdsa-private-key-recovery#setup

`python -m pip install -r requirements.txt`

try installing pycrypto via pip instead of setuptools too. other than that, make sure python and python-dev + all libs required to compile pycrypto are available in your system. (checkout the pycrypto install guide)
